
# 主机名 例如: http://spf13.com/
baseURL =  "https://github.com/adminfanf/adminfanf.github.io.git"
# 语言编码(中文: zh-CN)


# 自动检测是否包含中文/日文/韩文，该参数会影响摘要和字数统计功能，建议设置为true
hasCJKLanguage =              false

# 若为 false，`Getting Started` 这样的英文标签将会被转换为 `getting-started`
preserveTaxonomyNames =       true

# 设置使用的主题名称 (默认储存在 /themes/THEMENAME/)
theme = "mod"     

# 分页
paginate =                    10
paginatePath =                "page"

# 启用 Emoji; see emoji-cheat-sheet.com
enableEmoji =                 false

# 创建robots.txt，建议设置为true
enableRobotsTXT =             false

# 定义文章访问路径，详细见下文"URL管理" See "content-management/urls/"
permalinks =                  ""
