BaseURL = "https://fanfan.github.io"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "个人博客"
Theme = "mod"
pygmentsStyle = "default"
pygmentsUseClasses = true

[Author]
 Name = "username"

[outputs]
 home = [ "RSS", "HTML" ]

[outputFormats] 
 [outputFormats.RSS]
   mediatype = "application/rss"
   baseName = "feed"

[Params]

 BottomIntroduce = "个人微信"
 Subtitle = "Talk is cheap,show me code."
 Imglogo = "img/logo.jpg"
 AuthorImg = "img/wechat.jpg"
 DateFormat = "2019年10月24日"
 MonthFormat = "2019年10月"
 FancyBox = false

 [Params.Disqus]
   ShortName = "helloworld"

 [Params.Strings]
   Search = "搜索"
   PageNotFound = "你访问的页面不存在"
   ShowSideBar = "显示侧边栏"
   HideSideBar = "隐藏侧边栏"
   Categories = "分类"
   Archive = "归档"
   Tags = "标签"
   Rss = "RSS 订阅"
   TableOfContents = "文章目录"

[Menu]
 [[Menu.Main]]
   Name = "首页"
   URL = "/"
   Weight = 1
 [[Menu.Main]]
   Name = "关于"
   URL = "/about"
   Weight = 2
